apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 10.10.26.136
etcd:
  endpoints:
  - https://10.10.26.136:2379
  - https://10.10.26.137:2379
  - https://10.10.26.138:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
  - 10.10.26.120
apiServerExtraArgs:
  endpoint-reconciler-type: lease
