apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: egress
  template:
    metadata:
      labels:
        app: egress
    spec:
      containers:
      - name: egress
        image: zhuangweikang/operator_image:0.01
        ports:
        - containerPort: 30030
