apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ingress
    spec:
      containers:
      - name: ingress
        image: zhuangweikang/operator_image
        ports:
        - containerPort: 2340
