apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper-2
        service: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zhuangweikang/zookeeper
          env:
            - name: ZK_MYID
              value: "2"
            - name: ZK_NUMBER_OF_NODES
              value: "3"
            - name: ZK_SERVICE_NAME
              value: "zookeeper"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
      volumes:
        - emptyDir: {}
          name: data
