---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  labels:
    service: zookeeper
spec:
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: election
      port: 3888
  selector:
    name: zookeeper-3
